### ISSUE TITLE
Design a custom scrollbar

### ISSUE THREAD

**Issue by PH7N** [BlueprintFramework/web#13]
As of now, the website uses the default scrollbar supplied by the browser, this really doesn't fit in with the rest of the website and changing the scrollbar to assimilate shouldn't be a problem.

![image](https://github.com/BlueprintFramework/web/assets/120841550/ac26f9e7-de5c-49a4-ad47-2d73081f1aae)

**Comment by imlayered** [comment]
I fixed this in https://github.com/BlueprintFramework/web/pull/14
